#!/usr/bin/env bash
# Check if all 4 parameters are provided
if [ $# -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign variables to the input parameters
path_to_file=$1
ip_address=$2
username=$3
path_to_ssh_key=$4

# Transfer file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip_address:~/"
