#!/usr/bin/env bash
# A bash script that installs nginx and setup a simple Hello world page
sudo apt update
sudo apt upgrade -y
sudo apt install -y nginx
sudo echo "Hello World!" >/var/www/html/index.html
sudo service nginx restart
