#!/usr/bin/env bash
# Update package repositories and install Nginx
sudo apt update && sudo apt upgrade
sudo apt install nginx

# Define the custom header in Nginx configuration
sudo sed -i '/http {/a add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo systemctl restart nginx
