#!/usr/bin/env bash
# MySQL Backup Script for all databases
current_date=$(date +'%d-%m-%Y')

# Define the file names
dump_file="backup.sql"
archive_file="${current_date}.tar.gz"

# MySQL dump command
mysqldump --all-databases -u root -p"$1" >"$dump_file"

# Compress the dump file into a tar.gz archive
tar -czvf "$archive_file" "$dump_file"
