#!/usr/bin/env bash
# Loops from 1 to 10 and displays bad luck for
# 4th and goodluck for 8th position

counter=1

while [ $counter -le 10 ]; do
    if [[ $counter -eq 4 ]]; then
        echo "bad luck"
    elif [[ $counter -eq 8 ]]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
