#!/usr/bin/env bash
# Loops from 1 to 20 and echo something to the terminal
index=0

while [ $index -le 20 ]; do
    case $index in
    4)
        echo "bad luck from China"
        ;;

    9)
        echo "bad luck from Japan"
        ;;

    17)
        echo "bad luck from Italy"
        ;;

    *)
        echo $index
        ;;
    esac
    ((index++))
done
